# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sgx.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sgx.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tsgx.proto\"\x17\n\x06\x46uncId\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1b\n\nFuncResult\x12\r\n\x05value\x18\x01 \x01(\x05\x32/\n\nSecureFunc\x12!\n\x07SGXFunc\x12\x07.FuncId\x1a\x0b.FuncResult\"\x00\x62\x06proto3'
)




_FUNCID = _descriptor.Descriptor(
  name='FuncId',
  full_name='FuncId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='FuncId.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=36,
)


_FUNCRESULT = _descriptor.Descriptor(
  name='FuncResult',
  full_name='FuncResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='FuncResult.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=65,
)

DESCRIPTOR.message_types_by_name['FuncId'] = _FUNCID
DESCRIPTOR.message_types_by_name['FuncResult'] = _FUNCRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FuncId = _reflection.GeneratedProtocolMessageType('FuncId', (_message.Message,), {
  'DESCRIPTOR' : _FUNCID,
  '__module__' : 'sgx_pb2'
  # @@protoc_insertion_point(class_scope:FuncId)
  })
_sym_db.RegisterMessage(FuncId)

FuncResult = _reflection.GeneratedProtocolMessageType('FuncResult', (_message.Message,), {
  'DESCRIPTOR' : _FUNCRESULT,
  '__module__' : 'sgx_pb2'
  # @@protoc_insertion_point(class_scope:FuncResult)
  })
_sym_db.RegisterMessage(FuncResult)



_SECUREFUNC = _descriptor.ServiceDescriptor(
  name='SecureFunc',
  full_name='SecureFunc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=67,
  serialized_end=114,
  methods=[
  _descriptor.MethodDescriptor(
    name='SGXFunc',
    full_name='SecureFunc.SGXFunc',
    index=0,
    containing_service=None,
    input_type=_FUNCID,
    output_type=_FUNCRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SECUREFUNC)

DESCRIPTOR.services_by_name['SecureFunc'] = _SECUREFUNC

# @@protoc_insertion_point(module_scope)
